image: python:3.9

variables:
  WORK_DIR: .
cache:
  key: '$CI_COMMIT_REF_SLUG'
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - deploy
  tags:
    - team-11-runner
  script:
    - docker stop $(docker ps -aq) || true
    - echo "team 11"

